name: Django Tests CI

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup pyenv
      run: |
        curl https://pyenv.run | bash
        export PATH="$HOME/.pyenv/bin:$PATH"
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv virtualenv-init -)"
        pyenv --version
    - name: Install pyenv versions
      run: |
        pyenv install 3.8.13
        pyenv activate 3.8.13
        python -m pip install --upgrade pip
        pip install tox
    - name: Run tox
      run: tox
