name: Django Tests CI

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup pyenv
      run: |
        curl https://pyenv.run | bash
        export PATH="$HOME/.pyenv/bin:$PATH"
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv virtualenv-init -)"
        pyenv --version
